# compile options
LTO_ENABLE = yes
OPT = 3

# debug
CONSOLE_ENABLE = no
DEBUG_ENABLE = no
# CONSOLE_ENABLE = yes
# DEBUG_ENABLE = yes

# rgb
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no

# key overrides
KEY_OVERRIDE_ENABLE = yes

# nkro
NKRO_ENABLE = yes

# via/vial
VIA_ENABLE = no
VIAL_ENABLE = no
VIAL_INSECURE = no
VIALRGB_ENABLE = no

# disable other unneeded qmk features
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
COMMAND_ENABLE = no
DYNAMIC_TAPPING_TERM_ENABLE = no
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
EXTRAKEY_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MIDI_ENABLE = no
MOUSEKEY_ENABLE = no
OLED_ENABLE = no
QMK_SETTINGS = no
RING_BUFFERED_6KRO_REPORT_ENABLE = no
SEND_STRING_ENABLE = no
UNICODE_ENABLE = no