#pragma once

#define NKRO_DEFAULT_ON true
#define DEBOUNCE 20
#define EE_HANDS

#define WS2812_DI_PIN D3
#define RGBLED_NUM 72
#define RGBLIGHT_LED_COUNT RGBLED_NUM
#define RGBLIGHT_SPLIT
#define RGBLED_SPLIT { 36, 36 }
#define RGBLIGHT_LIMIT_VAL 120

// #define RGBLIGHT_CORRECTION_SCALE_G 0.72
// #define RGBLIGHT_CORRECTION_SCALE_B 0.83
// #define RGBLIGHT_CORRECTION_MAX_S 0.95